### ISSUE TITLE
parallel 3d projector gives zero result

### ISSUE THREAD

**Issue by adler-j** [astra-toolbox/astra-toolbox#18] opened 2016-01-13 14:17 UTC
Creating a `parallel3d_vec` geometry with `rayX = 0` causes a "empty" zero output. I think it has something to do with the block direction logic inside [par3d_fp](https://github.com/astra-toolbox/astra-toolbox/blob/master/cuda/3d/par3d_fp.cu).

Edit: it may be more complicated than this, however the following vectors all reproduce the result:

```
[ 0.          0.          1.          0.          0.          0.          0.     0.10752688  0.          0.10752688  0.          0.        ]
[ 0.          0.9839519  -0.17843389  0.          0.          0.          0.    -0.01918644 -0.10580128  0.10752688  0.          0.        ]
[ 0.          0.34293367  0.93935962  0.          0.          0.          0.     0.10100641 -0.03687459  0.10752688  0.          0.        ]
[ 0.         -0.85864109  0.51257729  0.          0.          0.          0.     0.05511584  0.092327    0.10752688  0.          0.        ]
```

Further examples:

This vector causes the bug:

```
[ 0.0099995   0.          0.99995     0.          0.          0.          0.  0.10752151  0.          0.10752688  0.          0.        ]
```

but this one does not:

```
[ 0.009999    0.009999    0.99990001  0.          0.          0.          0.  0.10751613 -0.00107516  0.10752688  0.          0.        ]
```

**Comment by wjp** [comment] 2016-01-13 16:06
Thanks, I can indeed reproduce this, and will investigate.

**Comment by wjp** [comment] 2016-01-13 22:23
At first glance it looks like this is an early-cutoff optimization (new in 1.7) that's deciding there's nothing to do in this case. I should have a patch this week.

**Comment by adler-j** [comment] 2016-01-14 08:44
Thank you very much!

**Comment by wjp** [comment] 2016-01-14 10:08
This should be fixed by 86ed34e9a5fa408c9338cd5c2871f7f7953806b7.

**Comment by wjp** [comment] 2016-01-14 10:35
Oh, and I've also added this geometry to my regression tests.

**Comment by adler-j** [comment] 2016-01-14 11:47
Great, suppose this can be closed then. Will this be made available in a patch anytime soon? (Thinking about the windows installers).

**Comment by wjp** [comment] 2016-01-14 13:06
There are a few more patches in the pipeline (such as the locale one), so I might do a 1.7.2 soon.

**Comment by wjp** [comment] 2016-01-14 13:09
This is not the right place for this comment, but as an aside: our current CUDA code is rather slow for rotating around the x or y axis (in astra's terminology), because of 3D texture cache locality issues.

**Closed** 2016-01-18 16:54 UTC
