### ISSUE TITLE
Bug in combination with non-English locale

### ISSUE THREAD

**Issue by moosmann** [astra-toolbox/astra-toolbox#16] opened 2015-11-26 19:10 UTC
I observed a very strange behaviour when trying to create a figure with matplotlib and afterwards creating an ASTRA 2D sinogram:

Running the script below from the shell or the within the PyCharm IDE leaves the shell unresponsive. The corresponding python process starts to run at 100% CPU usage and needs to be killed explicitly. In the Spyder IDE this does not happen when using the IPython console (with inline backend `'module://IPython.kernel.zmq.pylab.backend_inline'`) but when using the python console it does. Also this does not happen when `astra.data2d.create` is called before `plt.imshow`, or when a volume `'-vol'` is created instead of a sinogram, or when only 1, 2, 3 or 5 (or maybe another number of) angels are used. Turning the interactive mode of pyplot off or on with `plt.ioff()` or `plt.ion()` has no effect.

```
#!/usr/bin/env python

import astra
import numpy as np
import matplotlib.pyplot as plt


plt.figure(1)
plt.imshow(np.ones((4, 4)))

astra.data2d.create('-sino',
    astra.create_proj_geom('parallel', 1.0, 2, np.linspace(0, 1, 4)), 0)
```

I tested it with various combination of
* Python 2.7.6
* Python 3.4.3
* matplotlib 1.5.0
* matplotlib 1.4.3
* PyCharm 5.0.1
* Spyder 2.3.7 with Python 2.7.6, IPython 3.2.2, matplotlib 1.4.3
* numpy 1.10.1
* scipy 0.16.1
* latest ASTRA version from github
* graphical backend: Qt4Agg, GTK3Agg, GTKAgg, GTKCairo, GTK3Cairo, WXAgg

**Comment by dmpelt** [comment] 2015-11-27 09:56
That is very strange! I just tested the script above with Python 3.4.3, matplotlib 1.5.0, and the github master branch, and I don't get the same strange behavior. 

Can you try just doing something like `a = np.linspace(0,1,4)` instead of the `astra` call to see whether it might be a matplotlib/numpy bug? The reason I am asking is that the `linspace` call is probably also not used in the `'-vol'` call you tried, and that one does seem to work.

If it doesn't crash, could you try separating each step in the astra call, and putting print statements in each line, such as:

```python
ang = np.linspace(0,1,4)
print '1'
geom = astra.create_proj_geom('parallel',1.0,2,ang)
print '2'
astra.data2d.create('-sino',geom,0)
print '3'
```

Then you can see at which point the crash/hang occurs.

If everything fails, a fresh install of astra/numpy/matplotlib or just you entire python environment might work as well.

**Comment by moosmann** [comment] 2015-11-27 10:42
The crash is related to calling `astra.data2d.create` with argument `'-sino'`. Creating a volume data object or executing any other command it works. It also crashes when I run it in virtual environments. Probably it's some weird interplay of my system components.

**Comment by wjp** [comment] 2015-11-27 11:31
Could you try with the following line to define ang?

ang = np.linspace(0,1,4).astype(np.float64)

**Comment by moosmann** [comment] 2015-11-27 11:43
Didn't work. I also reinstalled ASTRA with a make distclean and removing all ASTRA related files beforehand. But the error remains. I also ran it under a different account on the same machine, but still the same.

**Comment by wjp** [comment] 2015-11-27 15:52
This sounds very confusing, and probably something to look at with gdb, valgrind, and such.

Is it on a KTH machine? I'll be there for two weeks in December, so if you want, we could also take a look together then.

**Comment by moosmann** [comment] 2015-11-27 16:46
Indeed it is very confusing, and annoying if your machine gets clutter with processes running at 100% cpu usage.
Yes, it is a KTH machine. Let's take a look together when you're at KTH.

**Comment by wjp** [comment] 2015-12-15 15:36
It turns out the problem is to do with locales. The bug occurs with locale set to de_DE.UTF-8.

When matplotlib is loaded, most likely it applies the global locale, and then boost::lexical_cast respects this, which causes the XML for the geometry to look like

    0,0,333333333333,0,666666666666,1
instead of

    0,0.333333333333,0.666666666666,1

Note the decimal comma.

(The actual hang then occurs because we try to get the angle 333333333333 between 0 and 2pi by repeatedly subtracting 2pi, which does nothing because of the limited floating point precision.)

We should make sure our XML generation is locale-independent.

**Comment by wjp** [comment] 2015-12-17 10:03
I'll replace our use of boost::lexical_cast by a set of utility functions in the astra namespace, probably using boost::spirit internally, or maybe with string streams explicitly imbued with the C locale. I'll experiment a bit to see what works conveniently.

**Comment by wjp** [comment] 2016-01-05 10:17
It still needs some more testing, but this should be fixed by https://github.com/wjp/astra-toolbox/commits/strings

**Closed** 2016-01-18 16:47 UTC
