### ISSUE TITLE
Cuda memory error

### ISSUE THREAD

**Issue by vlibX** [astra-toolbox/astra-toolbox#347] opened 2022-10-07 14:07 UTC
Hello !
I am using a script to reconstruct an unusual geometry (vertical fan beam on a linear detector, translated step by step).
I have only 60 projections of 1792*980 pixels.  The reconstructed volume is 400*250*250 voxels.  I use a nvidia rtx 3090 with 24Go RAM.

I was nicely provided a reconstruction script that worked very well when the sinogram was downsampled from a factor 4.
Given I have much than enough memory, I decided to try and reconstruct with the full sinogram.
I then obtained this error message:

Error: CUDA error 11: invalid argument.
Error: Failed to allocate 1792x58800x1 GPU array
Error: CUDA error 11: invalid argument.
Assertion failed: err == cudaSuccess, file E:/wjp/git/astra-toolbox/cuda/3d/util3d.cu, line 383

Could anyone please help me with this issue ?

V.

**Comment by askorikov** [comment] 2022-12-12 09:46
Hi! Could you maybe post the full script (well the part related to reconstruction) if you couldn't resolve this problem in the end?

**Comment by askorikov** [comment] 2022-12-12 11:54
I'm not sure if I understood correctly what type of geometry you have, but there is a dedicated fanflat geometry type in Astra (https://www.astra-toolbox.com/apiref/creators.html#astra.creators.create_proj_geom). I think using it (if applicable) could solve this CUDA error.

**Comment by vlibX** [comment] 2022-12-12 13:22
Hi Alexander,

I attached a picture that describes our geometry.  Basically, we have a 
1D detector, placed vertically. The barrel to be imaged is sequentially 
translated in front of the detector.  Hence, the geometry is neither a 
cone beam nor a fan beam CT.

Domenico Iuso wrote the script for us. Here is his take at the memory issue:

"

I confirm my assumption: on the CUDA programming guide ( 
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#features-and-technical-specifications__technical-specifications-per-compute-capability 
) it is written that there is an hard-limit on the size for the 
allocated 3D arrays, which is the one you are hitting on dimension 2.

It can, though, be solved, but the solution involves some programming: 
The usual geometries of Astra have a 2D detector and a certain number of 
views (the memory representation is [first detector line, views, second 
detector line]), while in this case there is a much higher number of 
views (to compensate the 1D detector) - so both the [number of rotation 
* number of line shifts] go on the second index of the allocated 3D 
array on memory. Since the third index is merely 1 because of 1D 
detector, it can be possible to unfold the data that is in the second 
index and put it on the third index. Once that is done, I see no further 
reasons why it should not work for the dimensionality of the data you 
have, even on a regular GPU.

"

**Comment by askorikov** [comment] 2022-12-12 14:48
The picture didn't get attached I guess, but I agree with Domenico (at least the first point, the second one will depend on geometry).

**Comment by askorikov** [comment] 2023-04-03 12:10
Closing the issue. Let us know if the problem is still relevant.

**Closed by askorikov** 2023-04-03 12:10 UTC
