### ISSUE TITLE
2D CPU FBP with axis of rotation offset

### ISSUE THREAD

**Issue by pierrethibault** [astra-toolbox/astra-toolbox#262] opened 2020-12-16 21:35 UTC
Hello,

This code snippet used to work (some time ago) but isn't working any more:

```python
import numpy as np
import imageio
import astra

tomo = imageio.imread('https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/SheppLogan_Phantom.svg/512px-SheppLogan_Phantom.svg.png').mean(axis=-1)

N = 512

# Astra tomogram
vol_geom = astra.create_vol_geom(N, N)
vol_id = astra.data2d.create('-vol', vol_geom)

# Astra sinogram
proj_geom = {'type': 'parallel',
             'DetectorWidth': 1.0,
             'DetectorCount': N,
             'ProjectionAngles': np.pi*np.arange(360)/360.}
sino_id = astra.data2d.create('-sino', proj_geom)

# Astra projector
proj_id = astra.create_projector('linear', proj_geom, vol_geom)

# Forward projection
cfg = astra.astra_dict('FP')
cfg['ProjectorId'] = proj_id
cfg['ProjectionDataId'] = sino_id
cfg['VolumeDataId'] = vol_id
fp_id = astra.algorithm.create(cfg)

# Run
astra.data2d.store(vol_id, tomo)
astra.algorithm.run(fp_id)
sinogram = astra.data2d.get(sino_id)

# Simulate detector offset and apply detector shift on projection geometry
sinogram = np.roll(sinogram, 10, axis=1)
proj_geom = astra.functions.geom_postalignment(proj_geom, 10)
proj_id = astra.create_projector('linear', proj_geom, vol_geom)
sino_id = astra.data2d.create('-sino', proj_geom)

# Filtered backprojection
cfg = astra.astra_dict('FBP')
cfg['ReconstructionDataId'] = vol_id
cfg['ProjectionDataId'] = sino_id
cfg['ProjectorId'] = proj_id
fbp_id = astra.algorithm.create(cfg)

astra.data2d.store(sino_id, sinogram)
astra.algorithm.run(fbp_id)
reconstruction = astra.data2d.get(vol_id)
```

The problem appears to be the check added in [`FilteredBackProjectionAlgorithm.cpp`](https://github.com/astra-toolbox/astra-toolbox/blob/74f822299c0292a77a0dfdf79a8cee4a2d4b6c1d/src/FilteredBackProjectionAlgorithm.cpp#L170-L174) which, as far as I understand, rejects the vector-based projection geometry created by [`geom_postalignment`](https://github.com/astra-toolbox/astra-toolbox/blob/10d87f45bc9311c0408e4cacdec587eff8bc37f8/python/astra/functions.py#L276).

The only workaround I have found up to now is to filter the sinogram myself and use 'BP'. Would it be possible to replace the check in `FilteredBackProjectionAlgorithm.cpp` to allow for 'parallel_vec' geometries as well?

**Comment by wjp** [comment] 2021-11-23 13:11
This issue is still unresolved, but closing as it is a duplicate of #226.

**Closed by wjp** 2021-11-23 13:11 UTC
