### ISSUE TITLE
Bug in 3D forward projector applied to large volumes

### ISSUE THREAD

**Issue by bwohlberg** [astra-toolbox/astra-toolbox#534] opened 2024-12-18 01:05 UTC
The 3D forward project produces corrupted results (presumably related to a pointer overflow) when applied to large volumes on GPUs with large memory. The following script should print two zero errors if the forward projector is functioning correctly:
```python
import astra
import numpy as np


def rmse(x, y):
    return np.sqrt(np.mean((x - y) ** 2))


N = 2048 + 1
vol = np.zeros((N, N, N), dtype=np.float32)
N4 = N // 4
vol[N4:-N4, N4:-N4, N4:-N4] = 1.0

input_shape = vol.shape
vol_geom = astra.create_vol_geom(input_shape[1], input_shape[2], input_shape[0])

det_count = (N, N)
det_spacing = (1.0, 1.0)
angles = np.linspace(0, np.pi/2, N, dtype=np.float32)
proj_geom = astra.create_proj_geom(
    "parallel3d",
    det_spacing[0],
    det_spacing[1],
    det_count[0],
    det_count[1],
    angles,
)

astra.set_gpu_index(0)
id, proj = astra.create_sino3d_gpu(vol, proj_geom, vol_geom)
astra.data3d.delete(id)


err0 = rmse(proj[:, 0], proj[:, -1])        # Views at 0 an pi/2 are the same when err0 == 0
err1 = rmse(proj[:, 0], 2 * N4 * vol[N4])   # View at 0 matches expected form when err1 == 0
print(f"Errors: {err0:.3e}  {err1:.3e}")
```
Large errors are reported on an A100 GPU with 80GB of RAM when N >= 2049, while zero errors are reported for N <= 2048. There does not appear to be any value of N resulting in large errors for GPUs with much less RAM, e.g.  GeForce RTX 2080 with 12 GB. The bug appears to depend on both the volume size and the number of views: it was not possible to find a value of N giving large errors when only two views were computed.

The host on which the errors were observed is running Linux x86_64 and has CUDA 12.5 and the following packages from conda-forge:
```
astra-toolbox             2.2.0           cudapy312h4ff3b56_102    conda-forge
libastra                  2.2.0           cuda11.8h658bec2_101    conda-forge
```

**Comment by bwohlberg** [comment] 2024-12-18 01:08
The nature of the view corruption depends on the volume size. The first example here is for a significantly larger volume
![astra_bug1](https://github.com/user-attachments/assets/005d761b-7f21-4040-9c00-6b41cdf406c1)
than the second example
![astra_bug2](https://github.com/user-attachments/assets/15dcd9f7-fbe5-4a08-8a76-2f0c811bc086)
In both cases the result should be a solid square.

**Comment by wjp** [comment] 2024-12-18 14:25
Could you enable debugging with `astra.log.setOutputFile('astra.log', astra.log.DEBUG)` and attach the resulting `astra.log` file a case that's failing? I'd also be interested in the output of `astra.get_gpu_info()` to see if RAM and compute capability were detected correctly.

**Comment by bwohlberg** [comment] 2024-12-18 16:49
The output from `astra.get_gpu_info()` is
```
'GPU #0: NVIDIA A100-SXM4-80GB, with 81157MB, CUDA compute capability 8.0'
```
which appears to be correct.

The `astra.log` file is attached below:
[astra.log](https://github.com/user-attachments/files/18186273/astra.log)

**Comment by wjp** [comment] 2024-12-18 20:45
Thank you for the log. I have a hypothesis for what's going wrong there and I'll do some experiments to confirm, which I think I can do on a smaller GPU. If I build conda packages with a potential fix and upload those to my personal conda channel, would you be willing to test those on the A100?

**Comment by bwohlberg** [comment] 2024-12-18 20:53
Thanks for the fast response on this bug report. Yes, absolutely, I'm happy to help with any testing necessary to resolve the problem.

**Comment by wjp** [comment] 2024-12-20 12:38
Great, thanks! I've uploaded some conda packages (version 2.2.0-100) to my personal channel now, for cuda >= 11.8 and python >= 3.10:

```
conda create -n astra-test -c wjpalenstijn -c nvidia python astra-toolbox
```


These packages (should) fix two issues that would start happening with GPU RAM sizes of around 48GB: one index overflow in the kernel (which hopefully is the cause of the corruption you are seeing), and one too small upper bound that makes us not fully use the available memory in this case (which wouldn't have caused corruption, but made things maybe less efficient).

I hope this fixes the corruption issues for you. In either case, could you upload a new log file so that I can evaluate if the new behaviour is what I'm expecting?

**Comment by askorikov** [comment] 2024-12-20 12:42
I guess  #173 would also be addressed by this?

**Comment by wjp** [comment] 2024-12-20 12:58
Unfortunately not. This particular patch won't impact GPUs with "only" 32GB. I would guess there it's more likely to be that the splitting algorithm allocates memory to output blocks first and input blocks only after that, and also tries to make all blocks of similar size during each individual splitting step. Both of those effects can cause memory to be left unused.

**Comment by bwohlberg** [comment] 2024-12-20 16:16
Thanks again for the very fast response. The test script reports 0 errors when run with the the astra 2.2.0-100 packages. The log file is attached.

[astra.log](https://github.com/user-attachments/files/18212859/astra.log)

**Comment by wjp** [comment] 2024-12-20 16:49
That's great to hear! The log looks as expected now too. We have a new release planned early next year, so this fix will be in that.

If you need a workaround with our current release on the A100 in the meantime, it's possible to limit the amount of memory that astra uses with a call like `astra.set_gpu_index(0, memory=40*(1024**3))`, which should keep things below the overflows. (We don't check that the number you pass there is smaller than the actual amount of memory, though.) 

Thank you for the detailed bug report and the quick testing, and happy holidays!

**Comment by bwohlberg** [comment] 2024-12-21 01:45
> If you need a workaround with our current release on the A100 in the meantime, it's possible to limit the amount of memory that astra uses with a call like `astra.set_gpu_index(0, memory=40*(1024**3))`, which should keep things below the overflows. (We don't check that the number you pass there is smaller than the actual amount of memory, though.)

Thanks for the suggestion on the workaround.
 
> Thank you for the detailed bug report and the quick testing, and happy holidays!

Thank you for the very fast response in resolving a bug that's been rather problematic for us. And likewise, happy holidays to you too.

**Closed** 2024-12-21 09:38 UTC
