### ISSUE TITLE
Crash after a lot of 3D reconstructions

### ISSUE THREAD

**Issue by NadavLisovtsev** [astra-toolbox/astra-toolbox#212] opened 2019-09-17 08:09 UTC
It looks like I have an error similar to #157  and #24 .
The main difference is that I have this error only after about 200 reconstructions (_SIRT3D_CUDA_ algorithm)
I am using Astra version 1.9.0dev on Python 3.5.4, with cudatoolkit 9.0.

Full error:
`Error: CUDA error 2: out of memory.
Error: Failed to allocate 823x70x854 GPU array
Error: CUDA error 11: invalid argument.
Assertion failed: err == cudaSuccess, file D:/wjp/miniconda3/conda-bld/libastra_1535461249666/work/cuda/3d/util3d.cu,line383`

Thanks

**Comment by wjp** [comment] 2021-11-26 13:48
I have tried many SIRT iterations with the new version 2.0 but do not see any memory leaks currently. Is it possible other applications or Windows started using more GPU memory during the reconstruction? I will close this issue as I cannot reproduce it currently, but feel free to re-open it if it still occurs for you with the current ASTRA version.

**Closed by wjp** 2021-11-26 13:48 UTC
